// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvJApr3MZinzUnj3kTmXftsUCavhvFj9M',
    appId: '1:715669702916:web:3e9fd689b21ba03264e851',
    messagingSenderId: '715669702916',
    projectId: 'musicapp-5000c',
    authDomain: 'musicapp-5000c.firebaseapp.com',
    storageBucket: 'musicapp-5000c.appspot.com',
    measurementId: 'G-L6D7GGX2Z5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB719zhuqiLSs3rqOVDRGOzDMChA76OSM0',
    appId: '1:715669702916:android:127206dd7e8e142464e851',
    messagingSenderId: '715669702916',
    projectId: 'musicapp-5000c',
    storageBucket: 'musicapp-5000c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvl7eKzdlX499HXPZC6orFdInvCWPHWng',
    appId: '1:715669702916:ios:42968a0ba0cb199264e851',
    messagingSenderId: '715669702916',
    projectId: 'musicapp-5000c',
    storageBucket: 'musicapp-5000c.appspot.com',
    iosClientId: '715669702916-2qvgo752hf66mucgf2bio8v32mhouef0.apps.googleusercontent.com',
    iosBundleId: 'com.example.musicApp',
  );
}
